### PR TITLE
Support speaker configuration panel and variable number of channels

### PR DESCRIPTION
**Pull request by amurzeau**
This PR is rather large but still.

These are the features implemented:
- Fix static analysis warnings reported by VS 2017
- Enable POOL_NX_OPTIN as reported by the driver verifier on Windows 10 (this has an effect only on Windows 8+)
- Add a topology filter. This complicate things a bit but should be better as existing audio devices always have both a wave filter and topology filter (both real hardware or virtual audio cables)
- Remove the unused clockRegister (replaced by a reserved field)
- Support the "Configure" button in the audio devices control panel
  - This allow to have the benefit of Windows mixing taking care of different channels. Like playing 4.0 audio on a 5.1 configured endpoint, this will output the rear channels on the matching rear channel of the 5.1 setup instead of center and LFE channels.
  - This is implemented by changing the endpoint category to SPEAKER from LINE_CONNECTOR
- Allow to playback with less channels than the endpoint has. Like playing 2.0 stereo on a 6 channels endpoint.
  - This is implemented by adding a register containing the actual number of channels on the WaveRT side, and filling only the enabled channel in SarAsio (silencing others)
- Fix crashes and various bugs when hammering endpoint creating and destruction
- Support Int16, Int24 and Int32 on SarAsio side. Each sample type is represented by its size (2, 3 or 4 bytes) on WaveRT side.
- Add more logging categories. I actually added somewhat verbose logs but I don't think it is a good idea to remove them all. These logs could be useful in case of a failure encountered by an user. Same for the Irp dump, I just kept it non compiled inside #ifdef, this can be useful.
- I had to put some KS WAVERT properties in #if because they were not defined when targeting  Windows 7. Like KSPROPERTY_RTAUDIO_PRESENTATION_POSITION. You were targeting Windows 10 before and it was still ok on Windows 7 ? The disabled properties are return STATUS_NOT_IMPLEMENTED so this should not have any effect.

I'm myself using my modified driver, but with windows in test mode as I don't have any certificate.
I've tested it mostly (ie. including stress tests) in Windows 10 1511 and 1803, but also on Windows 8.1 and windows 7.

### CODE REVIEW

**Comment by pannal** [comment]
@amurzeau would you share your builds so we can test your changes? I'm more than willing to enable testsigning for that :)

**Comment by amurzeau** [comment]
I've added some commits to makes building on appveyor possible (with an upgrade to VS 2017 as I only have that one).
Binaries will be available here: https://ci.appveyor.com/project/amurzeau/synchronousaudiorouter/build/artifacts

They are not signed, so to be able to run the driver, you will need to enable testsigning boot flag:
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option

Thank's for your testing :)
I'm using that driver myself now with jack so I can do audio routing between channels and DSP filters.

**Comment by amurzeau** [comment]
Also, ensure you uninstalled the previous SAR driver installation, else Windows might prefer to use the existing driver as it was signed.
The driver version should be 23.48.50.371.

**Comment by pannal** [comment]
I've contacted you on the SAR Discord to not further pollute this PR.

**Comment by amurzeau** [comment]
I've been running this on Windows 8.1 x64 since that PR without any issues while using hibernation, merging now.

**Pull request merged**
